services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passwordChangeInProduction
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2-0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passwordChangeInProduction

      KC_HOSTNAME: localhost

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./techradar-realm.json:/opt/keycloak/data/import/techradar-realm.json
    command: start-dev --http-enabled=true --import-realm
    depends_on:
      - postgres
    ports:
      - "8180:8080"

  mongodb:
    image: mongo:8.2.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passwordChangeInProduction
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongodb_data:
